---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    tier: backend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app
      tier: backend
  template:
    metadata:
      labels:
        app: app
        tier: backend
    spec:
      containers:
      - name: app
        image: levidurfee/pg-app
        resources:
          requests:
            cpu: 10m
            memory: 15Mi
          limits:
            cpu: 30m
            memory: 45Mi
---
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    tier: backend
spec:
  selector:
    app: app
    tier: backend
  ports:
  - protocol: TCP
    port: 9000
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app
  namespace: default
spec:
  maxReplicas: 100
  minReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app
  targetCPUUtilizationPercentage: 65
